### ISSUE TITLE
Set up logic for email verification after user signs up (use magic link from supabase or another vendor)

### ISSUE THREAD

**Issue by dave-cao** [Firm-Collective/ai-journal#20]
- Sendgrid ~ 1000 emails per day

- [ ] Look for an email vendor to send the verification email

**Comment by Lyton505** [comment]
The cheapest option seems to be Amazon SES...by far. Sendgrid is 100/day not 1K/day. If they're already using AWS then SES seems like a decent option here

**Comment by Lyton505** [comment]
@dave-cao  Do we really want to use [groups](https://docs.expo.dev/router/layouts/#groups) in the app navigation, because it's getting a little tricky to route app links to a specific page. E.g on clicking https://lyton.dev/(auth)/loginNewDummy I want users to go to the login page welcoming them, but I have to escape the 2 parentheses such that it now looks like https://lyton.dev/\(auth\)/loginNewDummy and for some reason, the last bit(\(auth\)/loginNewDummy) is getting cut off in the email sent

**Comment by dave-cao** [comment]
@Lyton505 Groups are useful because we don't need to but the "(auth)" portion within the url to get to the page. So to access the specific login page you would go **https://lyton.dev/loginNewDummy** instead of **https://lyton.dev/(auth)/loginNewDummy**.

It's a way to group pages together without having a clunkly url.

**Comment by Lyton505** [comment]
fyi @dave-cao , we still need to fix ios app links. The docs are [here](https://docs.expo.dev/guides/deep-linking/)
